import base from './index.js';

const enc=new TextEncoder();
const json=(body,status=200,headers={})=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const uid=()=>crypto.randomUUID();
const token=(n=48)=>[...crypto.getRandomValues(new Uint8Array(n))].map(x=>x.toString(16).padStart(2,'0')).join('').slice(0,n);
const clean=(s,n=2000)=>String(s??'').trim().slice(0,n);
const bool=v=>v?1:0;
const mediaUrl=key=>key?`/media/${encodeURIComponent(key)}`:null;
const cookie=(req,name)=>req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.split('=').slice(1).join('=');
const sessionCookie=(sid,maxAge=604800,secure=true)=>`ss_session=${sid}; Path=/; HttpOnly; SameSite=Lax; ${secure?'Secure; ':''}Max-Age=${maxAge}`;
const ALL={can_edit_branding:1,can_manage_media:1,can_manage_albums:1,can_view_rsvp:1,can_manage_guestbook:1,can_download:1,can_edit_features:1};

async function hash(value,salt){const key=await crypto.subtle.importKey('raw',enc.encode(value),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:100000,hash:'SHA-256'},key,256);return [...new Uint8Array(bits)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function portalUser(req,env){const sid=cookie(req,'ss_session');if(!sid)return null;return env.DB.prepare("SELECT users.id,users.email,users.role,users.is_active FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.id=? AND sessions.expires_at > datetime('now') AND users.is_active=1").bind(sid).first()}
async function portalSchemaReady(env){try{await env.DB.prepare('SELECT role,is_active FROM users LIMIT 1').first();await env.DB.prepare('SELECT event_id FROM client_event_access LIMIT 1').first();return true}catch{return false}}
async function access(env,u,eventId){if(!u)return null;const e=await env.DB.prepare('SELECT * FROM events WHERE id=?').bind(eventId).first();if(!e)return null;if(u.role==='admin')return {...e,member_role:'admin',permissions:{...ALL}};if(e.owner_id===u.id)return {...e,member_role:'owner',permissions:{...ALL}};const co=await env.DB.prepare('SELECT role FROM cohosts WHERE event_id=? AND user_id=?').bind(eventId,u.id).first();if(co)return {...e,member_role:co.role||'editor',permissions:{...ALL}};const a=await env.DB.prepare('SELECT * FROM client_event_access WHERE event_id=? AND user_id=?').bind(eventId,u.id).first();if(!a)return null;return {...e,member_role:'client',permissions:{can_edit_branding:!!a.can_edit_branding,can_manage_media:!!a.can_manage_media,can_manage_albums:!!a.can_manage_albums,can_view_rsvp:!!a.can_view_rsvp,can_manage_guestbook:!!a.can_manage_guestbook,can_download:!!a.can_download,can_edit_features:!!a.can_edit_features}}}
async function managePayload(env,e,u){const [media,albums,guestbook,rsvps,reports,cohosts]=await Promise.all([
env.DB.prepare("SELECT media.*,(SELECT count(*) FROM likes WHERE media_id=media.id) likes,(SELECT count(*) FROM comments WHERE media_id=media.id) comments FROM media WHERE event_id=? ORDER BY created_at DESC").bind(e.id).all(),
env.DB.prepare('SELECT * FROM albums WHERE event_id=? ORDER BY sort_order,created_at').bind(e.id).all(),env.DB.prepare('SELECT * FROM guestbook WHERE event_id=? ORDER BY created_at DESC').bind(e.id).all(),env.DB.prepare('SELECT * FROM rsvps WHERE event_id=? ORDER BY created_at DESC').bind(e.id).all(),env.DB.prepare('SELECT reports.*,media.filename FROM reports LEFT JOIN media ON media.id=reports.media_id WHERE reports.event_id=? ORDER BY reports.created_at DESC').bind(e.id).all(),env.DB.prepare('SELECT users.email,cohosts.role,cohosts.user_id FROM cohosts JOIN users ON users.id=cohosts.user_id WHERE cohosts.event_id=?').bind(e.id).all()]);
const mapped=media.results.map(x=>({...x,url:mediaUrl(x.object_key),thumbnail_url:mediaUrl(x.thumbnail_key)}));const visible=e.permissions.can_manage_media?mapped:(e.permissions.can_manage_guestbook?mapped.filter(x=>x.is_guestbook):[]);return {event:e,permissions:e.permissions,media:visible,albums:(e.permissions.can_manage_albums||e.permissions.can_manage_media)?albums.results:[],guestbook:e.permissions.can_manage_guestbook?guestbook.results:[],rsvps:e.permissions.can_view_rsvp?rsvps.results:[],reports:e.permissions.can_manage_media?reports.results:[],cohosts:(u.role==='admin'||e.owner_id===u.id)?cohosts.results:[]}}

async function portal(req,env,url){
 const method=req.method,p=url.pathname.slice('/api/portal'.length); if(!await portalSchemaReady(env))return json({error:'Client portal database migration is not installed yet. Apply migration 0004_client_portal.sql.'},503);
 if(p==='/login'&&method==='POST'){const b=await req.json(),email=clean(b.email,180).toLowerCase(),password=String(b.password||'');const u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first();if(!u||u.is_active===0||await hash(password,u.password_salt)!==u.password_hash)return json({error:'Invalid email or password.'},401);const sid=token(64);await env.DB.prepare("INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,datetime('now','+7 day'))").bind(sid,u.id).run();return json({user:{id:u.id,email:u.email,role:u.role}},200,{'set-cookie':sessionCookie(sid,604800,url.protocol==='https:')})}
 if(p==='/logout'&&method==='POST'){const sid=cookie(req,'ss_session');if(sid)await env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(sid).run();return json({ok:true},200,{'set-cookie':sessionCookie('',0,url.protocol==='https:')})}
 const u=await portalUser(req,env);if(p==='/me')return json({user:u});if(!u)return json({error:'Unauthorized'},401);
 if(p==='/events'&&method==='GET'){let r;if(u.role==='admin')r=await env.DB.prepare("SELECT events.*,'admin' AS member_role FROM events ORDER BY created_at DESC").all();else if(u.role==='client')r=await env.DB.prepare("SELECT events.*,'client' AS member_role FROM events JOIN client_event_access ON client_event_access.event_id=events.id WHERE client_event_access.user_id=? ORDER BY events.created_at DESC").bind(u.id).all();else r=await env.DB.prepare("SELECT events.*,CASE WHEN owner_id=? THEN 'owner' ELSE 'editor' END member_role FROM events WHERE owner_id=? OR EXISTS(SELECT 1 FROM cohosts WHERE event_id=events.id AND user_id=?) ORDER BY created_at DESC").bind(u.id,u.id,u.id).all();return json({events:r.results})}
 let m=p.match(/^\/events\/([^/]+)\/manage$/);if(m&&method==='GET'){const e=await access(env,u,m[1]);if(!e)return json({error:'Event not found or not assigned to this account.'},404);return json(await managePayload(env,e,u))}
 m=p.match(/^\/events\/([^/]+)$/);if(m&&method==='PATCH'){const e=await access(env,u,m[1]);if(!e)return json({error:'Not found'},404);const b=await req.json();const branding=['name','event_date','welcome_message','primary_color','theme','font_family'],features=['moderation_enabled','allow_downloads','allow_comments','allow_rsvp','strip_image_metadata','max_upload_mb','allow_photo_uploads','allow_video_uploads','allow_written_guestbook','allow_video_guestbook','allow_audio_guestbook','allow_gallery','allow_slideshow','allow_albums'];if(branding.some(k=>Object.prototype.hasOwnProperty.call(b,k))&&!e.permissions.can_edit_branding)return json({error:'Branding permission is disabled.'},403);if(features.some(k=>Object.prototype.hasOwnProperty.call(b,k))&&!e.permissions.can_edit_features)return json({error:'Feature settings permission is disabled.'},403);await env.DB.prepare(`UPDATE events SET name=?,event_date=?,welcome_message=?,primary_color=?,theme=?,font_family=?,moderation_enabled=?,allow_downloads=?,allow_comments=?,allow_rsvp=?,strip_image_metadata=?,max_upload_mb=?,allow_photo_uploads=?,allow_video_uploads=?,allow_written_guestbook=?,allow_video_guestbook=?,allow_audio_guestbook=?,allow_gallery=?,allow_slideshow=?,allow_albums=? WHERE id=?`).bind(clean(b.name??e.name,120),b.event_date??e.event_date,clean(b.welcome_message??e.welcome_message,500),clean(b.primary_color??e.primary_color,20),clean(b.theme??e.theme,30),clean(b.font_family??e.font_family,30),bool(b.moderation_enabled??e.moderation_enabled),bool(b.allow_downloads??e.allow_downloads),bool(b.allow_comments??e.allow_comments),bool(b.allow_rsvp??e.allow_rsvp),bool(b.strip_image_metadata??e.strip_image_metadata),Math.max(5,Math.min(100,+b.max_upload_mb||e.max_upload_mb||50)),bool(b.allow_photo_uploads??e.allow_photo_uploads),bool(b.allow_video_uploads??e.allow_video_uploads),bool(b.allow_written_guestbook??e.allow_written_guestbook),bool(b.allow_video_guestbook??e.allow_video_guestbook),bool(b.allow_audio_guestbook??e.allow_audio_guestbook),bool(b.allow_gallery??e.allow_gallery),bool(b.allow_slideshow??e.allow_slideshow),bool(b.allow_albums??e.allow_albums),e.id).run();return json({ok:true})}
 m=p.match(/^\/events\/([^/]+)\/albums$/);if(m&&method==='POST'){const e=await access(env,u,m[1]);if(!e)return json({error:'Not found'},404);if(!e.permissions.can_manage_albums)return json({error:'Album permission is disabled.'},403);const b=await req.json(),id=uid(),key=token(20);await env.DB.prepare('INSERT INTO albums(id,event_id,name,access_key,is_private,sort_order) VALUES(?,?,?,?,?,?)').bind(id,e.id,clean(b.name,100)||'Album',key,bool(b.is_private),+b.sort_order||0).run();return json({id,access_key:key},201)}
 m=p.match(/^\/media\/([^/]+)$/);if(m&&(method==='PATCH'||method==='DELETE')){const row=await env.DB.prepare('SELECT * FROM media WHERE id=?').bind(m[1]).first(),e=row?await access(env,u,row.event_id):null;if(!row||!e)return json({error:'Not found'},404);if(!e.permissions.can_manage_media)return json({error:'Media management permission is disabled.'},403);if(method==='DELETE'){await env.MEDIA.delete(row.object_key);if(row.thumbnail_key)await env.MEDIA.delete(row.thumbnail_key);await env.DB.prepare('DELETE FROM media WHERE id=?').bind(row.id).run();return json({ok:true})}const b=await req.json();if(b.status!==undefined&&['approved','pending','hidden'].includes(b.status))await env.DB.prepare('UPDATE media SET status=? WHERE id=?').bind(b.status,row.id).run();if(b.album_id!==undefined)await env.DB.prepare('UPDATE media SET album_id=? WHERE id=?').bind(b.album_id||null,row.id).run();return json({ok:true})}
 m=p.match(/^\/reports\/([^/]+)$/);if(m&&method==='PATCH'){const r=await env.DB.prepare('SELECT * FROM reports WHERE id=?').bind(m[1]).first(),e=r?await access(env,u,r.event_id):null;if(!r||!e)return json({error:'Not found'},404);if(!e.permissions.can_manage_media)return json({error:'Media management permission is disabled.'},403);const b=await req.json();await env.DB.prepare('UPDATE reports SET status=? WHERE id=?').bind(b.status==='resolved'?'resolved':'open',r.id).run();return json({ok:true})}
 m=p.match(/^\/events\/([^/]+)\/export$/);if(m&&method==='GET'){const e=await access(env,u,m[1]);if(!e)return json({error:'Not found'},404);if(!e.permissions.can_download)return json({error:'Download permission is disabled.'},403);const [media,guestbook,rsvps,albums]=await Promise.all([env.DB.prepare('SELECT * FROM media WHERE event_id=?').bind(e.id).all(),env.DB.prepare('SELECT * FROM guestbook WHERE event_id=?').bind(e.id).all(),env.DB.prepare('SELECT * FROM rsvps WHERE event_id=?').bind(e.id).all(),env.DB.prepare('SELECT * FROM albums WHERE event_id=?').bind(e.id).all()]);return json({exported_at:new Date().toISOString(),event:e,media:media.results,guestbook:guestbook.results,rsvps:rsvps.results,albums:albums.results})}
 if(p==='/admin/clients'&&method==='GET'){if(u.role!=='admin')return json({error:'Admin access required.'},403);const clients=await env.DB.prepare("SELECT id,email,role,is_active,created_at FROM users WHERE role='client' ORDER BY created_at DESC").all();for(const c of clients.results){const a=await env.DB.prepare('SELECT client_event_access.*,events.name event_name FROM client_event_access JOIN events ON events.id=client_event_access.event_id WHERE user_id=? ORDER BY events.created_at DESC').bind(c.id).all();c.assignments=a.results}return json({clients:clients.results})}
 if(p==='/admin/clients'&&method==='POST'){if(u.role!=='admin')return json({error:'Admin access required.'},403);const b=await req.json(),email=clean(b.email,180).toLowerCase();let password=String(b.password||'');if(!/^\S+@\S+\.\S+$/.test(email))return json({error:'Use a valid email.'},400);if(!password)password=`Snap-${token(14)}`;if(password.length<10)return json({error:'Password must be at least 10 characters.'},400);if(await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return json({error:'That email is already registered.'},409);const id=uid(),ps=token(32),rs=token(32),recovery=token(24).toUpperCase();await env.DB.prepare("INSERT INTO users(id,email,password_hash,password_salt,recovery_hash,recovery_salt,role,is_active) VALUES(?,?,?,?,?,?,'client',1)").bind(id,email,await hash(password,ps),ps,await hash(recovery,rs),rs).run();return json({client:{id,email,is_active:1},temporary_password:password,recovery_code:recovery},201)}
 m=p.match(/^\/admin\/clients\/([^/]+)$/);if(m&&method==='PATCH'){if(u.role!=='admin')return json({error:'Admin access required.'},403);const b=await req.json();await env.DB.prepare("UPDATE users SET is_active=? WHERE id=? AND role='client'").bind(bool(b.is_active),m[1]).run();return json({ok:true})}
 m=p.match(/^\/admin\/clients\/([^/]+)\/assignments\/([^/]+)$/);if(m&&method==='PUT'){if(u.role!=='admin')return json({error:'Admin access required.'},403);const b=await req.json();await env.DB.prepare(`INSERT INTO client_event_access(event_id,user_id,can_edit_branding,can_manage_media,can_manage_albums,can_view_rsvp,can_manage_guestbook,can_download,can_edit_features) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(event_id,user_id) DO UPDATE SET can_edit_branding=excluded.can_edit_branding,can_manage_media=excluded.can_manage_media,can_manage_albums=excluded.can_manage_albums,can_view_rsvp=excluded.can_view_rsvp,can_manage_guestbook=excluded.can_manage_guestbook,can_download=excluded.can_download,can_edit_features=excluded.can_edit_features`).bind(m[2],m[1],bool(b.can_edit_branding),bool(b.can_manage_media),bool(b.can_manage_albums),bool(b.can_view_rsvp),bool(b.can_manage_guestbook),bool(b.can_download),bool(b.can_edit_features)).run();return json({ok:true})}if(m&&method==='DELETE'){if(u.role!=='admin')return json({error:'Admin access required.'},403);await env.DB.prepare('DELETE FROM client_event_access WHERE user_id=? AND event_id=?').bind(m[1],m[2]).run();return json({ok:true})}
 return json({error:'Not found'},404)
}

export default {async fetch(req,env){const url=new URL(req.url);if(url.pathname==='/client'||url.pathname==='/client/')return env.ASSETS.fetch(new Request(new URL('/client.html',url),req));if(url.pathname==='/admin'||url.pathname==='/admin/')return env.ASSETS.fetch(new Request(new URL('/admin.html',url),req));if(url.pathname.startsWith('/api/portal/'))return portal(req,env,url);
 if(url.pathname.startsWith('/api/')){let u=null,ready=false;try{ready=await portalSchemaReady(env);if(ready)u=await portalUser(req,env)}catch{}if(ready&&u?.role==='client'){
   if(url.pathname==='/api/events'&&req.method==='POST')return json({error:'Client accounts cannot create events.'},403);
   if(url.pathname==='/api/events'&&req.method==='GET'){url.pathname='/api/portal/events';return portal(req,env,url)}
   let m=url.pathname.match(/^\/api\/events\/([^/]+)\/manage$/);if(m&&req.method==='GET'){url.pathname=`/api/portal/events/${m[1]}/manage`;return portal(req,env,url)}
   m=url.pathname.match(/^\/api\/events\/([^/]+)$/);if(m&&req.method==='PATCH'){url.pathname=`/api/portal/events/${m[1]}`;return portal(req,env,url)}
   m=url.pathname.match(/^\/api\/media\/([^/]+)$/);if(m&&(req.method==='PATCH'||req.method==='DELETE')){url.pathname=`/api/portal/media/${m[1]}`;return portal(req,env,url)}
 }
 }
 return base.fetch(req,env)}};
