import base from './v141.js';

const json=(body,status=200,headers={})=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});
const cookie=(req,name)=>req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.split('=').slice(1).join('=');
async function me(req,env){const sid=cookie(req,'ss_session');if(!sid)return null;return env.DB.prepare("SELECT users.id,users.email,users.role,users.is_active FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.id=? AND sessions.expires_at > datetime('now') AND users.is_active=1").bind(sid).first()}
async function access(env,u,eventId){if(!u)return null;const e=await env.DB.prepare('SELECT * FROM events WHERE id=?').bind(eventId).first();if(!e)return null;if(u.role==='admin'||e.owner_id===u.id)return {event:e,can_edit:true};const co=await env.DB.prepare('SELECT user_id FROM cohosts WHERE event_id=? AND user_id=?').bind(eventId,u.id).first();if(co)return {event:e,can_edit:true};if(u.role!=='client')return null;const a=await env.DB.prepare('SELECT can_edit_branding FROM client_event_access WHERE event_id=? AND user_id=?').bind(eventId,u.id).first();return a?{event:e,can_edit:!!a.can_edit_branding}:null}
async function ready(env){try{await env.DB.prepare('SELECT slideshow_overlay_enabled,custom_logo_key FROM events LIMIT 1').first();return true}catch{return false}}
const clean=(s,n=160)=>String(s??'').trim().slice(0,n);
const extFor=t=>t==='image/png'?'.png':t==='image/webp'?'.webp':t==='image/svg+xml'?'.svg':'.jpg';

export default {async fetch(req,env,ctx){const url=new URL(req.url),method=req.method;let m=url.pathname.match(/^\/api\/portal\/events\/([^/]+)\/slideshow-branding$/);
  if(m){const u=await me(req,env);if(!u)return json({error:'Unauthorized'},401);if(!await ready(env))return json({error:'Apply migration 0008_slideshow_branding.sql first.'},503);const a=await access(env,u,m[1]);if(!a)return json({error:'Not found'},404);
    if(method==='GET')return json({settings:{slideshow_overlay_enabled:!!a.event.slideshow_overlay_enabled,slideshow_overlay_layout:a.event.slideshow_overlay_layout||'top',slideshow_overlay_title:a.event.slideshow_overlay_title||'Share the Memories',slideshow_overlay_subtitle:a.event.slideshow_overlay_subtitle||'Scan the QR code to share your photos',slideshow_banner_color:a.event.slideshow_banner_color||'#0b2d6b',slideshow_banner_opacity:Number(a.event.slideshow_banner_opacity??0.86),custom_logo_key:a.event.custom_logo_key||null,custom_logo_url:a.event.custom_logo_key?'/media/'+encodeURIComponent(a.event.custom_logo_key):null}});
    if(method==='PATCH'){if(!a.can_edit)return json({error:'Branding permission is disabled.'},403);const b=await req.json();const layouts=new Set(['top','bottom','right','left']);const layout=layouts.has(b.slideshow_overlay_layout)?b.slideshow_overlay_layout:'top';const opacity=Math.max(.25,Math.min(1,Number(b.slideshow_banner_opacity??.86)));const color=/^#[0-9a-f]{6}$/i.test(String(b.slideshow_banner_color||''))?b.slideshow_banner_color:'#0b2d6b';await env.DB.prepare('UPDATE events SET slideshow_overlay_enabled=?,slideshow_overlay_layout=?,slideshow_overlay_title=?,slideshow_overlay_subtitle=?,slideshow_banner_color=?,slideshow_banner_opacity=? WHERE id=?').bind(b.slideshow_overlay_enabled?1:0,layout,clean(b.slideshow_overlay_title,80)||'Share the Memories',clean(b.slideshow_overlay_subtitle,100)||'Scan the QR code to share your photos',color,opacity,m[1]).run();return json({ok:true})}
  }
  m=url.pathname.match(/^\/api\/portal\/events\/([^/]+)\/custom-logo$/);
  if(m&&(method==='POST'||method==='DELETE')){const u=await me(req,env);if(!u)return json({error:'Unauthorized'},401);if(!await ready(env))return json({error:'Apply migration 0008_slideshow_branding.sql first.'},503);const a=await access(env,u,m[1]);if(!a)return json({error:'Not found'},404);if(!a.can_edit)return json({error:'Branding permission is disabled.'},403);
    if(method==='DELETE'){if(a.event.custom_logo_key)await env.MEDIA.delete(a.event.custom_logo_key);await env.DB.prepare('UPDATE events SET custom_logo_key=NULL WHERE id=?').bind(m[1]).run();return json({ok:true,custom_logo_key:null})}
    const form=await req.formData();const file=form.get('file');if(!(file instanceof File)||!file.size)return json({error:'Choose a logo file.'},400);if(!['image/jpeg','image/png','image/webp','image/svg+xml'].includes(file.type))return json({error:'Logo must be PNG, JPG, WEBP, or SVG.'},400);if(file.size>5*1024*1024)return json({error:'Logo must be 5 MB or smaller.'},400);const key=`event-logos/${m[1]}/${crypto.randomUUID()}${extFor(file.type)}`;await env.MEDIA.put(key,file.stream(),{httpMetadata:{contentType:file.type,cacheControl:'public, max-age=86400'}});if(a.event.custom_logo_key)await env.MEDIA.delete(a.event.custom_logo_key);await env.DB.prepare('UPDATE events SET custom_logo_key=? WHERE id=?').bind(key,m[1]).run();return json({ok:true,custom_logo_key:key,custom_logo_url:'/media/'+encodeURIComponent(key)})
  }
  return base.fetch(req,env,ctx)
}};
